id: P007970
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137820
  title: ཏཱ་ལའི་བླ་མ་སྐུ་ཕྲེང་བཅུ་གསུམ་པས་སྲིད་གཞུང་གསར་བསྒྱུར་གྱི་མཛད་སྒོ་སྤེལ་བ་ལས་འཕྲོས་པའི་ལོ་རྒྱུས་ཀྱི་གཏམ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    50b72979541f4564914face9cc88d903:
      image_group_id: I2PD19654
      title: ''
      volume_number: 1
      total_pages: 542
ebook_metadata:
  title: ཏཱ་ལའི་བླ་མ་སྐུ་ཕྲེང་བཅུ་གསུམ་པས་སྲིད་གཞུང་གསར་བསྒྱུར་གྱི་མཛད་སྒོ་སྤེལ་བ་ལས་འཕྲོས་པའི་ལོ་རྒྱུས་ཀྱི་གཏམ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  sku: P007970
  cover: cover.jpg
  layers:
  - pagination
