id: opecha:P007970
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137820
  title: ཏཱ་ལའི་བླ་མ་སྐུ་ཕྲེང་བཅུ་གསུམ་པས་སྲིད་གཞུང་གསར་བསྒྱུར་གྱི་མཛད་སྒོ་སྤེལ་བ་ལས་འཕྲོས་པའི་ལོ་རྒྱུས་ཀྱི་གཏམ་ནོར་བུའི་མེ་ལོང་།
  volume: ''
  author: ''
