id: P007970
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:26.806881
source_metadata:
  id: bdr:W1PD137820
  title: ཏཱ་ལའི་བླ་མ་སྐུ་ཕྲེང་བཅུ་གསུམ་པས་སྲིད་གཞུང་གསར་བསྒྱུར་གྱི་མཛད་སྒོ་སྤེལ་བ་ལས་འཕྲོས་པའི་ལོ་རྒྱུས་ཀྱི་གཏམ་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    fe9c88d429d34f8e8e88896f5171f0d5:
      image_group_id: I2PD19654
      title: Volume 1 of tA la'i bla ma sku phreng bcu gsum pas srid gzhung gsar bsgyur
        gyi mdzad sgo spel ba las 'phros pa'i lo rgyus kyi gtam nor bu'i me long /
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
